### ISSUE TITLE
Install TITAL lyrics scraper fails

### ISSUE THREAD

**Issue by kec2** [arnesongit/plugin.audio.tidal2#19]
I have just intalled Tidal2 via repository 0.2.1.
LibreElec 11.0.1, kodi 20

In the Settings -> Options -> Install TIDAL lyrics scraper I get an error message:
TIDAL2 Fatal Error
NameError("name 'LYRIC_CWD' is not defined")

**Comment by arnesongit** [comment]
Did you install the "LCR Lyrics" addon ?
You can do this within the Settings -> Options -> "Install CU LRC Lyrics addon"

**Comment by kec2** [comment]
Hey

I tried: Settings -> Options -> "Install CU LRC Lyrics addon" and it failed.
I have not tried to install LCR Lyrics addon in any other way.

Regards
Klaus Christiansen

**Comment by arnesongit** [comment]
The lyrics addon is a standard addon for Kodi. You can install it from the Kodi repository under the "Lyrics" category. The "CU LRC Lyrics" addon is the only one. There is no other lyrics adddon.
After this you can try the settings option "Install TIDAL lyrics scraper", because this will add a new scraper module inside the CU LRC Lyrics source folder.
