### ISSUE TITLE
Update readme with login section

### ISSUE THREAD

**Issue by kec2** [arnesongit/plugin.audio.tidal2#20]
I have problems logging into Tidal and the description from host:5555/login is not helping.
ClientID and secret does not seam to be my Tidal credentials.
And what is TIDAL APK?

**Comment by arnesongit** [comment]
The ClientID and Secret are values to access the API calls on the TIDAL servers. There are a lot of possible ClientIDs because each device manufactor who wants to support TIDAL music has their own cedentials. And each device type supports different playback modes. For instance "Sony 360 Audio" is only available on Sony Android devices.

The TIDAL APK is the installation package file for Android devices. You can find TIDAK.apk files if you search for "TIDAL apk mirror" with google.

The ClientIDs and Credentials are stored in the APK file and my addon can pick them out of the apk file.
You have to open the apk in the addon settings first and select a device type. Then you can try to login with the url http://host:5555/login

**Comment by kec2** [comment]
Thanks.

I have now tried several devices and login fails.

http://host:555/login
`TIDAL2 - OAuth2 Login
Device Type°Hi Res 
Login-StatusNot logged in. Please login via web browser !

°Attention: Device type was selected from the TIDAL APK !
Client-ID are Client-Secret are fixed !`

Click Login

http://host:5555/login_step2?client_id=&client_secret=
`Login Failed !`

It seams that clientID and secret are not picket up.

**Comment by kec2** [comment]
Device type: TV worked and I was sent to Tidal.com to login with my own credentials. :-)

**Comment by arnesongit** [comment]
TIDAL uses two kinds of OAuth authentication methods, the code link method which works with the TIDAL2 addon and the PKCE method which TIDAL2 doesn't support yet. The device types "Default", "Clear", "Clear Dolby Atmos" and "Dolby Atmos" uses the PKCE method. So this device types can't be used for login.
But I'm alleady working on the PKCE support for TIDAL2.

**Comment by arnesongit** [comment]
README now contains log in informations.
