### ISSUE TITLE
Dolby Atmos not working anymore

### ISSUE THREAD

**Issue by PROVRS** [arnesongit/plugin.audio.tidal2#25]
Hello Arne,

Unfortunately Atmos stopped working after the update.

"WARNING <general>: [TIDAL2] Dolby AC4 not supported ! Playing silence track to avoid kodi to crash ..." 

Thanks for the HiRes by the way 😉

Running on Hardkernel ODROID-N2Plus with CoreELEC (official): 19.5-Matrix, kernel: Linux ARM 64-bit version 4.9.269
FFmpeg version/source: 4.3.2-Kodi
Host CPU: Amlogic S922X rev b, 6 cores available

edit: This error is when using "HiRes Atmos" from the apk during logon.
When using Automotive Atmos from the apk, Atmos songs are working but HiRes not.

**Comment by arnesongit** [comment]
If you use the device type 'Dolby Atmos Hi Res' the TIDAL servers uses Dolby-AC4 as a stream format for Atmos. Kodi isn't able to decode it so my addon is playing a silent track instead. Otherwise Kodi will crash.
There is no way to play Hi Res audio tracks and Dolby Atmos as Dolby-AC3 with any device type.
Please use the device type "Hi Res" or "Clear Hi Res" to play Hi Res music or "Automotive Dolby Atmos" if you want to play Dolby-AC3 streams.
I'm using the Kodi profiles for this. In one profile I set the Hi Res device type and in an other profile I have the Automotive Dolby Atmos type to play Dolby-AC3.
