### ISSUE TITLE
getting client id and secret

### ISSUE THREAD

**Issue by Tecko71** [arnesongit/plugin.audio.tidal2#3]
Can not find on the internet where to get client id and secret. So than the whole plugin is useless .

**Comment by arnesongit** [comment]
There is no client id and secret in the plugin. You have to download the tidal apk (Android app) and go the the addon settings where you can select the apk file to select a device type from the app.
Pleasee search the web for "tidal apk mirror" any you will find the apk to download.
But you have to download tidal apk version 2.63 or lower because tidal has changed something in the apk format from version 2.64 upwards.
The next tidal2 addon will be able to use every device type from the app.
At this point yo have to select an "automotive" or "tv" device type from the app. This will work.
