### ISSUE TITLE
Track is DRM protected

### ISSUE THREAD

**Issue by jbrepogmailcom** [arnesongit/plugin.audio.tidal2#34]
Hello. I have used ID and secret from thy python script and after login Tidal correctly shows my country and I can play movies. But when I select some album, I get message "Track is DRM protected" and it skips through all tracks in album. Any solution to that?

**Comment by tymoteuszsielach** [comment]
I also have this issue

**Comment by jbrepogmailcom** [comment]
I used other credentials that worked. From github project Tidal-Media-Downloader, file apiKey.py, last clientID and clientSecret (for platform TV)

**Comment by danielkochc** [comment]
This is due to the credentials. The ones that work allow master audio in flac and Dolby digital (atmos) but no "normal" audio tracks (DRM protected). The others mentioned by the previous speaker allow "all" formats, but only play them in stereo aac 2.0. So you have to decide whether you want to play all formats, but then only in aac stereo or in flac ~1.5mbit and Dolby digital 5.1/atmos with the most normal formats not working.

**Comment by jbrepogmailcom** [comment]
Sir you got me confused :-)  So what credentials do I need to use flac HiFi (CD PCM quality)? It is not master quality and I do not pay for master. Or what device to emulate? Thanks very much.
